from sqlalchemy.orm import Session
from app.repositories.reccomendation_repository import RecommendationRepository
from app.repositories.interaction_repository import InteractionRepository
from app.schemas.recommendation import RecommendationCreate
from app.models.recommendation import Recommendation
from app.services.ai_services import AIService
from fastapi import HTTPException, status

class RecommendationService:
    def __init__(self, db: Session):
        self.recommendation_repo = RecommendationRepository(db)
        self.interaction_repo = InteractionRepository(db)
        self.ai_service = AIService()

    def generate_recommendations(self, interaction_id: int) -> list[Recommendation]:
        """
        Takes a processed customer interaction, runs it through the AI Agent system,
        and saves the generated 'Next Best Actions' to the database.
        """
        # 1. Fetch the raw interaction text and context
        interaction = self.interaction_repo.get_by_id(interaction_id)
        if not interaction:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Interaction ID {interaction_id} not found."
            )

        # 2. Handoff context to the AI service (Planner / LangGraph Pipeline)
        ai_output = self.ai_service.analyze_interaction(
            content=interaction.content,
            interaction_type=interaction.interaction_type,
        )

        saved_recommendations = []

        # 3. Process and persist every recommendation generated by the AI
        for choice in ai_output.get("recommendations", []):
            rec_data = RecommendationCreate(
                interaction_id=interaction.id,
                customer_id=interaction.customer_id,
                action=choice["action"],
                confidence=choice["confidence"],
                reason=choice["reason"],
                status="Pending"
            )
            
            db_rec = self.recommendation_repo.create(rec_data)
            saved_recommendations.append(db_rec)

        return saved_recommendations

    def get_recommendation(self, recommendation_id: int) -> Recommendation:
        """
        Retrieves a single recommendation record.
        """
        recommendation = self.recommendation_repo.get_by_id(recommendation_id)
        if not recommendation:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Recommendation ID {recommendation_id} not found."
            )
        return recommendation

    def list_pending_recommendations(self) -> list[Recommendation]:
        """
        Fetches all un-reviewed recommendations awaiting human intervention.
        """
        return self.recommendation_repo.get_pending()