"""
Constants and configuration values used throughout the InsightFlow AI backend.
"""

# Recommendation statuses
RECOMMENDATION_STATUS_PENDING = "pending"
RECOMMENDATION_STATUS_APPROVED = "approved"
RECOMMENDATION_STATUS_REJECTED = "rejected"
RECOMMENDATION_STATUS_EXECUTED = "executed"

VALID_RECOMMENDATION_STATUSES = [
    RECOMMENDATION_STATUS_PENDING,
    RECOMMENDATION_STATUS_APPROVED,
    RECOMMENDATION_STATUS_REJECTED,
    RECOMMENDATION_STATUS_EXECUTED,
]

# Approval decisions
APPROVAL_DECISION_APPROVED = "approved"
APPROVAL_DECISION_REJECTED = "rejected"

VALID_APPROVAL_DECISIONS = [
    APPROVAL_DECISION_APPROVED,
    APPROVAL_DECISION_REJECTED,
]

# Interaction types
INTERACTION_TYPE_EMAIL = "email"
INTERACTION_TYPE_CALL = "call"
INTERACTION_TYPE_MEETING = "meeting"
INTERACTION_TYPE_SUPPORT_TICKET = "support_ticket"
INTERACTION_TYPE_FEEDBACK = "feedback"
INTERACTION_TYPE_OTHER = "other"

VALID_INTERACTION_TYPES = [
    INTERACTION_TYPE_EMAIL,
    INTERACTION_TYPE_CALL,
    INTERACTION_TYPE_MEETING,
    INTERACTION_TYPE_SUPPORT_TICKET,
    INTERACTION_TYPE_FEEDBACK,
    INTERACTION_TYPE_OTHER,
]

# Confidence score thresholds
MIN_CONFIDENCE_SCORE = 0.0
MAX_CONFIDENCE_SCORE = 1.0
HIGH_CONFIDENCE_THRESHOLD = 0.8
MEDIUM_CONFIDENCE_THRESHOLD = 0.5

# Pagination
DEFAULT_PAGE_SIZE = 100
MAX_PAGE_SIZE = 1000
MIN_PAGE_SIZE = 1

# Time-related constants
DEFAULT_APPROVAL_WINDOW_HOURS = 24
RECOMMENDATION_EXPIRY_DAYS = 30

# API Response Messages
MSG_CUSTOMER_CREATED = "Customer created successfully"
MSG_CUSTOMER_UPDATED = "Customer updated successfully"
MSG_CUSTOMER_DELETED = "Customer deleted successfully"
MSG_INTERACTION_CREATED = "Interaction recorded successfully"
MSG_RECOMMENDATION_CREATED = "Recommendation created successfully"
MSG_APPROVAL_CREATED = "Approval recorded successfully"
MSG_NOT_FOUND = "Resource not found"
MSG_VALIDATION_ERROR = "Validation error"
MSG_INTERNAL_ERROR = "Internal server error"

# Error codes
ERROR_CODE_CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND"
ERROR_CODE_INTERACTION_NOT_FOUND = "INTERACTION_NOT_FOUND"
ERROR_CODE_RECOMMENDATION_NOT_FOUND = "RECOMMENDATION_NOT_FOUND"
ERROR_CODE_APPROVAL_NOT_FOUND = "APPROVAL_NOT_FOUND"
ERROR_CODE_DUPLICATE_EMAIL = "DUPLICATE_EMAIL"
ERROR_CODE_INVALID_STATUS = "INVALID_STATUS"
ERROR_CODE_INVALID_DECISION = "INVALID_DECISION"
